<%@ Page Title="My Services" Language="C#" MasterPageFile="~/Employee/EmployeeMasterPage.master" AutoEventWireup="true" CodeFile="EmpServices.aspx.cs" Inherits="EmpServices" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
      <asp:HyperLink ID="HyperLink3" runat="server" NavigateUrl="~/Employee/EmpLogOutPage.aspx" style="float:right; position:relative;top:-45px; font-size:x-large; font-weight:bold; font-family:Garamond; left: 0px; height: 30px; width: 100px;" CssClass="links" BackColor="Black">Log Out</asp:HyperLink>

        <div style="float:left;width:49.5%; height:688px; text-align:center; border: yellow solid 2px;">
        <asp:label ID="Label3" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>SERVICE REQUESTS, PAYMENTS & EMAIL  </b> </asp:label>
        <div id="resProfile">

   <asp:label ID="Label12" runat="server" style="font-family:Garamond; color:white; font-size:xx-large; " ><b>Service Requests:</b> </asp:label>
             <br />
            <br />
            <asp:DetailsView ID="serviceRequestsView" runat="server" Height="50px" Width="693px" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" BackColor="#669999" BorderColor="White" BorderStyle="Solid" BorderWidth="2px" DataSourceID="SqlDataSource1" EmptyDataText="Not Available" Font-Bold="True" Font-Names="Garamond" Font-Size="X-Large" ForeColor="White">
                <Fields>
                    <asp:BoundField DataField="username" HeaderText="UserName" SortExpression="username" />
                    <asp:BoundField DataField="category" HeaderText="Category" SortExpression="category" />
                    <asp:BoundField DataField="RequestDate" HeaderText="RequestDate" SortExpression="RequestDate" />
                    <asp:BoundField DataField="Status" HeaderText="Status" SortExpression="Status" />
                    <asp:BoundField DataField="RequestDescription" HeaderText="RequestDescription" SortExpression="RequestDescription" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:RealEstateDBConnectionString %>" SelectCommand="SELECT [username], [category], [RequestDate], [Status], [RequestDescription] FROM [EstateServicesTable]" DeleteCommand="DELETE FROM EstateServicesTable WHERE (username = @username)" UpdateCommand="UPDATE EstateServicesTable SET username = @username, category = @category, RequestDate = @RequestDate, Status = @Status, RequestDescription = @RequestDescription">
                <DeleteParameters>
                    <asp:ControlParameter ControlID="serviceRequestsView" Name="username" PropertyName="SelectedValue" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:ControlParameter ControlID="serviceRequestsView" Name="username" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="serviceRequestsView" Name="category" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="serviceRequestsView" Name="RequestDate" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="serviceRequestsView" Name="Status" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="serviceRequestsView" Name="RequestDescription" PropertyName="SelectedValue" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
       
       <asp:label ID="paymentLabel" runat="server" style="font-family:Garamond; color:white; font-size:xx-large; " ><b>Payment Details :</b> </asp:label>
            
            <br />
            <br />
            <asp:GridView ID="paymentDetailsList" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#009999" BorderColor="White" BorderStyle="Solid" BorderWidth="1px" DataSourceID="SqlDataSource2" EmptyDataText="NotAvailable" Font-Names="Garamond" Font-Size="X-Large" ForeColor="White" Width="693px" PageSize="5" AutoGenerateColumns="False">
                <Columns>
                    <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
                    <asp:BoundField DataField="PaymentAmount" HeaderText="PaymentAmount" SortExpression="PaymentAmount" />
                    <asp:BoundField DataField="PaymentDate" HeaderText="PaymentDate" SortExpression="PaymentDate" />
                    <asp:BoundField DataField="Status" HeaderText="Status" SortExpression="Status" />
                    <asp:BoundField DataField="Type" HeaderText="Type" SortExpression="Type" />
                </Columns>
            </asp:GridView>
            
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:RealEstateDBConnectionString %>" SelectCommand="SELECT * FROM [EstateFundsTable]"></asp:SqlDataSource>
            
            
            <br />
            <br />
            <asp:Button runat="server" Text="Update Payments" Height="30px" Width="150px" Font-Bold="True" ID="updatePayments" Font-Size="medium" CausesValidation="False" OnClick="updatePayments_Click" />    
            
            <br />
            <br />
            
            <asp:label ID="sendEmailLabel" runat="server" style="font-family:Garamond; color:white; font-size:xx-large; " ><b>Send Email With UserName :</b> </asp:label>
            
            <br />
            <br />
            
                    <asp:label ID="emailUserName" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>User Name :</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <asp:TextBox ID="emailUserNameText" runat="server" Font-Size="X-Large" Width="216px"></asp:TextBox>
            <asp:RequiredFieldValidator ID="usernameReqValid" runat="server" ErrorMessage="* UserName is Required" BackColor="White" BorderColor="Maroon" BorderStyle="Solid" Display="Dynamic" ForeColor="#FF3300" BorderWidth="1px" Font-Bold="True" ControlToValidate="emailUserNameText" Font-Names="Garamond" Font-Size="large"></asp:RequiredFieldValidator>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ErrorMessage="* Please enter the Correct Format" BackColor="White" BorderColor="Maroon" BorderStyle="Solid" Display="Dynamic" ForeColor="#FF3300" BorderWidth="1px" Font-Bold="True" ControlToValidate="emailUserNameText" Font-Names="Garamond" Font-Size="large" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>     <br />
            <br />
                    <asp:label ID="Label18" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>Email Subject:</b> </asp:label>
            
            <br />
            <br />
            
                         <asp:TextBox ID="emailSubject" runat="server" Font-Size="X-Large" Width="216px"></asp:TextBox>

            <br />
            <br />
                    <asp:label ID="Label19" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>Email Description:</b> </asp:label>
            
            <br />
            <br />
                        <textarea id="emailContent" runat="server" cols="20" rows="4" style="width: 230px; font-size: large; height: 100px"></textarea>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="* Email Content is Required" BackColor="White" BorderColor="Maroon" BorderStyle="Solid" Display="Dynamic" ForeColor="#FF3300" BorderWidth="1px" Font-Bold="True" ControlToValidate="emailContent" Font-Names="Garamond" Font-Size="large"></asp:RequiredFieldValidator>
            <br />
            <br />
            <asp:Button runat="server" Text="Send Email" Height="30px" Width="150px" Font-Bold="True" ID="sendEmailButton" Font-Size="medium" OnClick="sendEmailButton_Click" />    
            
            <br />
            <br />
            <asp:label ID="emailSentLabel" runat="server" style="font-family:Garamond; color:white; font-size:x-large; "></asp:label>
            <br />
            <br />
</div>

    </div>
    

    <div style="float:left;width:49.5%; height:688px; margin-top:-30px;   text-align:center; border: brown solid 2px;">
    <asp:label ID="Label1" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>RESIDENT FACILITY ALLOTMENT </b> </asp:label>
        <div id="allotmentDetail">
                    <asp:label ID="Label2" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>List Of Facilities Available :</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:DropDownList ID="facilityList" runat="server" Height="39px" Width="346px" Font-Bold="True" Font-Names="Garamond" Font-Size="Larger" AutoPostBack="True"></asp:DropDownList>
            <br />
            <br />
                    <asp:label ID="Label4" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>User Name :</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <asp:TextBox ID="allotUsername" runat="server" Font-Size="X-Large" Width="216px"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="* UserName is Required" BackColor="White" BorderColor="Maroon" BorderStyle="Solid" Display="Dynamic" ForeColor="#FF3300" BorderWidth="1px" Font-Bold="True" ControlToValidate="allotUsername" Font-Names="Garamond" Font-Size="large"></asp:RequiredFieldValidator>
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" ErrorMessage="* Please enter the Correct Format" BackColor="White" BorderColor="Maroon" BorderStyle="Solid" Display="Dynamic" ForeColor="#FF3300" BorderWidth="1px" Font-Bold="True" ControlToValidate="allotUsername" Font-Names="Garamond" Font-Size="large" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>     <br />

            
            <br />
            <br />
                    <asp:label ID="Label6" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>Lease Join Date :</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <asp:TextBox ID="leaseJoinDate" runat="server" Font-Size="X-Large" Width="250px" ReadOnly="True"></asp:TextBox>
            <br />
            <br />
                    <asp:label ID="Label5" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>Duration Of Stay:</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:DropDownList ID="durationList" runat="server" Height="30px" Width="110px" AutoPostBack="True" OnSelectedIndexChanged="durationList_SelectedIndexChanged">
                <asp:ListItem Value="3">3 Months</asp:ListItem>
                <asp:ListItem Value="6">6 Months</asp:ListItem>
                <asp:ListItem Value="9">9 Months</asp:ListItem>
                <asp:ListItem Value="12">1 Year</asp:ListItem>
                <asp:ListItem Value="24">2 Years</asp:ListItem>
                <asp:ListItem Value="36">3 Years </asp:ListItem>
                <asp:ListItem Value="48">4 Years</asp:ListItem>
                <asp:ListItem Value="60">5 Years</asp:ListItem>
                    </asp:DropDownList>
            <br />
            <br />
            
                    <asp:label ID="Label7" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>Lease End Date :</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            
             <asp:TextBox ID="leaseEndDate" runat="server" Font-Size="X-Large" Width="240px" ReadOnly="True"></asp:TextBox>
            
            <br />
            <br />
            <asp:label ID="Label8" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>Facility Status :</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:DropDownList ID="facilityStatus" runat="server" Height="42px" Width="150px">
                <asp:ListItem>Available</asp:ListItem>
                <asp:ListItem>Occupied</asp:ListItem>
                    </asp:DropDownList>
            <br />
            <br />
                   
             <asp:label ID="Label9" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>Vehicle Facility :</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:DropDownList ID="vehicleFacility" runat="server" Height="43px" Width="150px">
             <asp:ListItem>Yes</asp:ListItem>
                <asp:ListItem>No</asp:ListItem>
               </asp:DropDownList>
            <br />
            <br />
                   
             <asp:label ID="Label10" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ><b>Pet Facility :</b> </asp:label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:DropDownList ID="petFacility" runat="server" Height="25px" Width="150px"> <asp:ListItem>Yes</asp:ListItem>
                <asp:ListItem>No</asp:ListItem>
               </asp:DropDownList>
            <br />
            <br />
                   
            <asp:Button runat="server" Text="Confirm Allotment" Height="40px" Width="170px" Font-Bold="True" ID="confirmAllotment" Font-Size="medium" OnClick="confirmAllotment_Click" />    
            
            <br />
            <br />
                   
             <asp:label ID="confirmLabel" runat="server" style="font-family:Garamond; color:white; font-size:x-large; " ></asp:label>
            

</div>

    </div>
    

</asp:Content>

